encyclopedia/views/account.py
from encyclopedia.views import *
from encyclopedia.forms import LoginForm, SignupForm, UpdateProfileForm
from flask_login import login_user, logout_user
from encyclopedia import hasher

import os
import secrets
from werkzeug.utils import secure_filename


accountbp = Blueprint('account', __name__)

# @accountbp.after_request 
# def after_request(response):
#     header = response.headers
#     header['Access-Control-Allow-Origin'] = '*'
#     # Other headers can be added here if needed
#     return response

@accountbp.route('/login', methods=['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        flash(f'You already have been logged in!', 'info')
        return redirect(url_for('general.home'))

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if not user:
            user = User.query.filter_by(username=form.email.data.lower()).first()        

        if user and hasher.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash(f'Logged as {user.username.capitalize()}!', 'success')
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('general.home'))
        else:
            flash(f'Login unsuccessful. Please check email/username and password', 'danger')

    return render_template('login.html', form=form)

@accountbp.route('/signup', methods=['POST', 'GET'])
def signup():
    if current_user.is_authenticated:
        flash(f'You already have been logged in!', 'danger')
        return redirect(url_for('general.home'))

    form = SignupForm()

    if form.validate_on_submit():
        user = User(form.username.data.lower(), form.email.data.lower(), form.password.data)
        db.session.add(user)
        db.session.commit()

        flash(f'Your account has been created! You are now able to log in!', 'success')
        return redirect(url_for('account.login'))

    return render_template('signup.html', form=form)

@accountbp.route('/logout')
def logout():
    logout_user()
    
    return redirect(url_for('general.home'))

@accountbp.route('/<username>', methods=['GET'])
@login_required
def account(username: str):
    user_account = User.query.filter_by(username=username).first() # user passed as an argument

    if not user_account:
        user_account = current_user
        return redirect(url_for('account.account', username=current_user.username))
    
    imagesrc = url_for('static', filename=f'profile_pictures/{user_account.profile_imagefile}')

    return render_template('account.html', user=user_account, imagesrc=imagesrc)

@accountbp.route('/edit/<id>', methods=['POST', 'GET'])
@login_required
def update_profile(id: int):
    try:
        user_account = User.query.filter_by(id=id).first() # user passed as an argument
    except sqlalchemy.exc.DataError:
        return redirect(url_for('errors.error404'))

    form = UpdateProfileForm()

    if (not user_account) or (user_account != current_user):
        user_account = current_user
        return redirect(url_for('account.account', username=current_user.username))

    if form.validate_on_submit():
        if form.picture.data:
            picture_filepath = upload_file(form.picture.data, current_user.id)
            current_user.profile_imagefile = picture_filepath

        current_user.username = form.username.data.lower()
        current_user.email = form.email.data.lower()
        
        db.session.commit()
        flash('Your account has been edited!', 'success')

        return redirect(url_for('account.account', username=current_user.username))
    
    elif request.method == 'GET':
        form.username.data = current_user.username.capitalize()
        form.email.data = current_user.email.capitalize()

    imagesrc = url_for('static', filename=f'profile_pictures/{user_account.profile_imagefile}')

    return render_template('update_profile.html', imagesrc=imagesrc, form=form)

def upload_file(form_file, user_id):
    new_filename = secrets.token_hex(8)
    new_filename += os.path.splitext(form_file.filename)[1]
    new_filename = secure_filename(new_filename)
    
    filedir = os.path.join(current_app.root_path, 'static', 'profile_pictures', str(user_id))
    if not os.path.isdir(filedir):
        print('Does not exist!', os.path.isfile(filedir))
        os.mkdir(filedir)
    
    filepath = os.path.join(filedir, new_filename)
    form_file.save(filepath)

    dbfilepath = f'{user_id}/{new_filename}'
    return dbfilepath

encyclopedia/views/general.py
from encyclopedia.views import *
from encyclopedia import redis_client
from encyclopedia.search import DefaultSearch, PyramidDataSearch

generalbp = Blueprint("general", __name__)


@generalbp.route("/", methods=["GET"])
def home():
    return render_template("home.html")


@generalbp.route("/about", methods=["GET"])
def about():
    return render_template("about.html")


@generalbp.route("/book", methods=["GET"])
def book():
    return render_template("education.html")


@generalbp.route("/not_found", methods=["GET"])
def not_found():
    query = request.args.get("q")
    if not query:
        return redirect(url_for("general.home", is_empty=1))

    return render_template("not_found.html", user_input=query)


@generalbp.route("/search", methods=["GET"])
def search():
    import json

    if not g.search_form.validate():
        return redirect(url_for("general.home"))

    user_input = g.search_form.q.data
    search_type = g.search_form.search_type.data
    search_type = "0" if search_type == None else search_type

    if user_input:
        try:
            results = json.loads(redis_client.get(f"{user_input}:{search_type}"))
            return render_template("search.html", results=results, q=user_input)
        except TypeError:
            if search_type == "0":
                search = DefaultSearch(db.session, user_input)
            elif search_type == "1":
                search = PyramidDataSearch(db.session, user_input)

            results = search.search()

            if not (results["exact"] or results["related"]):
                return redirect(url_for("general.not_found", q=user_input))

            redis_client.set(f"{user_input}:{search_type}", json.dumps(results))
            redis_client.expire(user_input, 3600)
            return render_template(
                "search.html",
                related=results["related"],
                exact=results["exact"],
                q=user_input,
            )

    flash("Something went wrong", "danger")
    return redirect(url_for("general.home"))


@generalbp.route("/choose_language", methods=["GET"])
def choose_language():
    if not g.choose_language_form.validate():
        return redirect(request.referrer)

    chosen_language = g.choose_language_form.language.data
    session["locale"] = chosen_language

    return redirect(request.referrer)

encyclopedia/views/pyramid.py
from encyclopedia.views import *
from encyclopedia.forms import (
    UploadPyramidForm,
    ConfirmPyramidDeletionForm,
    RelationSubform,
    ExplicitFormulaSubform,
    GeneratingFunctionSubform,
)

pyramidbp = Blueprint("pyramid", __name__)
POSTS_PER_PAGE = 20


@pyramidbp.after_request
def after_request(response):
    header = response.headers
    header["Access-Control-Allow-Origin"] = "*"
    # Other headers can be added here if needed
    return response


@pyramidbp.route("/<snid>", methods=["GET", "POST"])
def pyramid(snid: int):
    try:
        pyramid = Pyramid.query.filter_by(sequence_number=snid).first()
    except sqlalchemy.exc.DataError:
        return redirect(url_for("errors.error404"))

    if not pyramid:
        return redirect(url_for("errors.error404"))

    deleteform = ConfirmPyramidDeletionForm()

    if deleteform.validate_on_submit():
        if current_user.moderator:
            from encyclopedia.managers import PyramidManager

            PyramidManager(db.session).delete(pyramid)
            flash(
                f"The pyramid #{pyramid.sequence_number} has been successfully deleted!",
                "success",
            )

            return redirect(url_for("general.home"))

        return render_template("page_not_found.html"), 403

    return render_template(
        "pyramid.html", pyramid=pyramid, PyramidModel=Pyramid, deleteform=deleteform
    )


@pyramidbp.route("/list", methods=["GET"])
def pyramid_list():
    page = request.args.get("page")
    try:
        page = int(page)
    except:
        page = 1
    if not page:
        page = 1
    pyramid_list = Pyramid.query.order_by(Pyramid.sequence_number)
    pyramids = pyramid_list[(page - 1) * POSTS_PER_PAGE : (page) * POSTS_PER_PAGE]

    if not pyramids:
        return redirect(url_for("general.home", page=1))

    pages_in_total = len(pyramid_list.all()) // POSTS_PER_PAGE
    if len(pyramid_list.all()) % POSTS_PER_PAGE:
        pages_in_total += 1

    return render_template(
        "pyramid_list.html", pyramids=pyramids, page=page, pages_in_total=pages_in_total
    )


@pyramidbp.route("/upload", methods=["POST", "GET"])
@login_required
def upload_pyramid():
    if not current_user.moderator:
        flash("You have no access to this page", "danger")
        return redirect(url_for("general.home"))

    form = UploadPyramidForm()

    if form.validate_on_submit():
        try:
            alreadyExist = (
                Pyramid.query.filter_by(
                    sequence_number=form.sequenceNumber.data
                ).count()
                > 0
            )
            if alreadyExist:
                flash(f"Such pyramid already exists", "danger")
                return redirect(url_for("pyramid.upload_pyramid"))

            pyramid = Pyramid(form.sequenceNumber.data)

            rels = form.relations.data

            for i, gf in enumerate(form.generatingFunction):
                isMain = False
                if (
                    gf.f_name.data == "U"
                    or gf.f_name.data == "u"
                    or i == len(form.generatingFunction) - 1
                ):
                    isMain = True
                pyramid.add_generating_function(
                    gf.f_name.data, gf.f_vars.data, gf.f_expr.data, isMain
                )

            for ef in form.explicitFormula:
                pyramid.add_explicit_formula(
                    form.ef_vars.data, ef.f_expr.data, ef.f_condition.data
                )

            pyramid.init_special_value()
            alreadyExist = (
                Pyramid.query.filter_by(
                    __special_hashed_value__=pyramid.__special_hashed_value__
                ).count()
                > 0
            )

            if alreadyExist:
                flash(
                    f"Pyramid with such formulas probably already exists. Make sure generating function and explicit formula are unique",
                    "danger",
                )
                return redirect(url_for("pyramid.upload_pyramid"))

            db.session.add(pyramid)
            db.session.commit()

            for i, relation in enumerate(form.relations.data):
                try:
                    pyramid.add_relation(
                        Pyramid.query.filter_by(
                            sequence_number=relation.get("relatedto_pyramid")
                        )
                        .first()
                        .id,
                        relation.get("tag"),
                    )
                except Exception:
                    flash(
                        f"Could not add a relation between pyramids #{relation.get('relatedto_pyramid')} and #{pyramid.sequence_number}",
                        "danger",
                    )
                    return redirect(
                        url_for("pyramid.edit_pyramid", snid=pyramid.sequence_number)
                    )

            current_user.add_pyramid(pyramid)
            db.session.commit()
            flash("The pyramid has been added!", "success")

        except:
            flash("Could not process formulas!", "danger")

        return redirect(url_for("pyramid.pyramid", snid=pyramid.sequence_number))

    return render_template("upload_pyramid.html", form=form)


@pyramidbp.route("/<snid>/edit", methods=["POST", "GET"])
@login_required
def edit_pyramid(snid: int):
    from encyclopedia.models import relations

    if not current_user.moderator:
        flash("You have no access to this page", "danger")
        return redirect(url_for("general.home"))

    form = UploadPyramidForm()
    pyramid = Pyramid.query.filter_by(sequence_number=snid).first()

    if not pyramid:
        return render_template("page_not_found.html"), 404

    if form.validate_on_submit():
        try:
            for i, gf in enumerate(form.generatingFunction):
                isMain = False
                if (
                    gf.f_name.data == "U"
                    or gf.f_name.data == "u"
                    or i == len(form.generatingFunction) - 1
                ):
                    isMain = True

                try:
                    pyramid.generating_function[i].change_formula(
                        function_name=gf.f_name.data,
                        variables=gf.f_vars.data,
                        expression=gf.f_expr.data,
                    )
                except IndexError:
                    pyramid.add_generating_function(
                        gf.f_name.data, gf.f_vars.data, gf.f_expr.data, isMain
                    )

            for i, ef in enumerate(form.explicitFormula):
                try:
                    pyramid.explicit_formula[i].change_formula(
                        expression=ef.f_expr.data,
                        variables=form.ef_vars.data,
                        limitation=ef.f_condition.data,
                    )
                except IndexError:
                    pyramid.add_explicit_formula(
                        form.ef_vars.data, ef.f_expr.data, ef.f_condition.data
                    )

            pyramid.delete_all_relations()

            for i, relation in enumerate(form.relations.data):
                try:
                    pyramid.add_relation(
                        Pyramid.query.filter_by(
                            sequence_number=relation.get("relatedto_pyramid")
                        )
                        .first()
                        .id,
                        relation.get("tag"),
                    )
                except Exception as e:
                    print(e)
                    flash(
                        f"Could not add a relation between pyramids #{relation.get('relatedto_pyramid')} and #{pyramid.sequence_number}. Make sure pyramid #{relation.get('relatedto_pyramid')} exists",
                        "danger",
                    )
                    return redirect(
                        url_for("pyramid.edit_pyramid", snid=pyramid.sequence_number)
                    )

            db.session.add(pyramid)

            pyramid.init_special_value()
            db.session.commit()
            flash("The pyramid has been edited!", "success")

        except:
            flash("Could not process formulas!", "danger")

        return redirect(url_for("pyramid.pyramid", snid=pyramid.sequence_number))

    elif request.method == "GET":
        form.sequenceNumber.data = pyramid.sequence_number

        if pyramid.generating_function:
            form.generatingFunction[0].f_name.data = pyramid.generating_function[
                0
            ].function_name
            form.generatingFunction[0].f_vars.data = pyramid.generating_function[
                0
            ].get_variables_as_str()
            form.generatingFunction[0].f_expr.data = pyramid.generating_function[
                0
            ].expression

        if pyramid.explicit_formula:
            form.ef_name.data = pyramid.explicit_formula[0].function_name
            form.ef_vars.data = pyramid.explicit_formula[0].get_variables_as_str()
            form.explicitFormula[0].f_expr.data = pyramid.explicit_formula[0].expression
            form.explicitFormula[0].f_condition.data = pyramid.explicit_formula[
                0
            ].limitation

        for i in range(len(pyramid.generating_function) - 1):
            gf = pyramid.generating_function[i + 1]
            gform = GeneratingFunctionSubform()
            gform.f_name = gf.function_name
            gform.f_vars = gf.get_variables_as_str()
            gform.f_expr = gf.expression
            form.generatingFunction.append_entry(gform)

        for i in range(len(pyramid.explicit_formula) - 1):
            ef = pyramid.explicit_formula[i + 1]
            eform = ExplicitFormulaSubform()
            eform.f_expr = ef.expression
            eform.f_condition = ef.limitation
            form.explicitFormula.append_entry(eform)

encyclopedia/templates/about.html
{% extends 'base.html' %} {% block head %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='stylesheets/aboutstyle.css') }}"
/>
<title>About</title>
{% endblock %} {% block body %}

<body>
  <div class="lists">
    {{ _('Project team') }} :<br />
    <!--  -->
    {{ _('"Laboratoriya algoritmov i tekhnologij issledovaniya diskretnyh struktur" stuff') }}<br />
    <!--  -->
    {{ _('TUSUR students - group project training participants') }}
    <!-- Студенты ТУСУР - участники Группового проектного обучения -->
  </div>
  <div class="content">
    <div class="image">
      <div class="image_first exmpl">
        <img src="../static/images/image_one.jpg" />
      </div>
    </div>
    <div class="textAboutUs">
      <strong>
        {{ _('"Laboratoriya algoritmov i tekhnologij issledovaniya diskretnyh struktur" (LATIDS) of the Faculty of "KSUP"') }}
        <!-- Лаборатория алгоритмов и технологий исследования дискретных структур (ЛАТИДС) кафедры КСУП  --> </strong
      ><br />
      {{ _('Leading Researcher') }}
      <!-- Ведущий научный сотрудник -->
      <br />
      <strong>
        {{ _('Kruchinin Dmitry Vladimirovich') }}
        <!-- Кручинин Дмитрий Владимирович --> </strong
      ><br />
      <i>
        {{ _('Candidate of Physical and Mathematical Sciences') }}
        <!-- Кандидат физико-математических наук -->
        <br />
        {{ _('Head of the Laboratory') }}
        <!-- Заведующий лабораторией --> </i
      ><br />
    </div>
  </div>
  <div class="lists">
    <div>
      <strong>
        {{ _('LATIDS stuff') }} :
        <!-- Сотрудники ЛАТИДС: --> </strong
      ><br />
      {{ _('Kruchinin Vladimir Viktorovich') }}
      <!-- Кручинин Владимир Викторович  -->
      -
      <i>
        {{ _('Doctor of Technical Sciences, Associate Professor') }}
        <!-- доктор технических наук, доцент --> </i
      ><br />

      {{ _('Perminova Maria Yurievna') }}
      <!-- Перминова Мария Юрьевна -->
      -
      <i>
        {{ _('Candidate of Technical Sciences, Senior Researcher') }}
        <!-- кандидат технических наук, старший научный сотрудник --> </i
      ><br />
      {{ _('Shablya Yuri Vasilyevich') }} -
      <i>
        {{ _('Candidate of Technical Sciences, Senior Researcher') }}
        <!-- кандидат технических наук, старший научный сотрудник --> </i
      ><br />
    </div>
    <div>
      <strong>
        {{ _('Group Project Training participants') }} :
        <!-- Группа ГПО: --> </strong
      ><br />
      {{ _('Alina Polina Sergeevna') }}<br />
      {{ _('Darizhapov Artem Batoevich') }}<br />
      {{ _('Kontsevaya Kristina Anatolyevna') }}<br />
      {{ _('Korneeva Yulia Andreevna') }}
    </div>
  </div>
</body>
{% endblock %}

encyclopedia/templates/header_search.html
<link
  rel="stylesheet"
  href="{{ url_for('static',filename='stylesheets/header_search.css') }}"
/>
<div class="search-div">
  {% if g.search_form %}
  <form
    method="get"
    class="search-form"
    action="{{ url_for('general.search') }}"
  >
    <div class="search-wrapper">
      <div
        class="input-wrapper"
        data-tooltip="
{{ _('Default: 
    by pyramid\'s 
        sequence number, 
        generating function, 
        explicit formula,
    by user\'s 
        username;
By data:
    by pyramid\'s
         data table (which you can see on pyramid\'s page specifically).')}}
                "
        data-tooltip-location="bottom"
        data-tooltip-additional-location="left"
        data-tooltip-textalign="left"
      >
        {{ g.search_form.search_type(class="search_type") }} {{ g.search_form.q(
        type="text", class="question", placeholder=_('Search...'),
        autocomplete="off") }}

        <!-- </label> -->
        <button type="submit" class="questionbtn" id="questionbtn">
          <span class="material-icons">search</span>
        </button>
      </div>
    </div>
  </form>
  {% endif %}
</div>

encyclopedia/templates/not_found.html
{% extends 'base.html' %} {% block head %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='stylesheets/not_foundstyle.css') }}"
/>
<title>{{ user_input }}</title>
{% endblock %} {% block header %} {% include 'header_search.html' %} {% endblock
%} {% block body %}
<main>
  <div class="notfound">
    <span
      >{{ _('Your search') }} -<b>
        {% if user_input|length > 25 %}{{ user_input[0:25] }}...{% else %}{{
        user_input }}{% endif %} </b
      >- {{ _('did not match anything') }}.</span
    >
    <span
      >{{ _('Try going back') }} <a href="/">{{ _('home') }}</a> {{ _('and perform another search') }}.</span
    >
  </div>
</main>
{% endblock %}

encyclopedia/templates/page_not_found.html
{% extends 'base.html' %} {% block head %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='stylesheets/not_foundstyle.css') }}"
/>
<title>Page not found</title>
{% endblock %} {% block header %} {% include 'header_search.html' %} {% endblock
%} {% block body %}
<main>
  <div class="notfound">
    <span
      >{{ _('Sorry, there\'s no such page. You can try going') }}
      <a href="/">{{ _('home') }}</a> {{ _('and explore pyramids.') }}</span
    >
  </div>
</main>
{% endblock %}

encyclopedia/templates/pyramid_list.html
{% extends 'base.html' %} {% block head %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/katex.min.css" integrity="sha384-KiWOvVjnN8qwAZbuQyWDIbfCLFhLXNETzBQjA/92pIowpC0d2O3nppDGQVgwd2nB" crossorigin="anonymous">
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/katex.min.js" integrity="sha384-0fdwu/T/EQMsQlrHCCHoH10pkPLlKA1jL5dFyUOvB3lfeT2540/2g6YgSi2BL14p" crossorigin="anonymous"></script>
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/pyramid_liststyle.css') }}">
<title>Pyramid list</title>
{% endblock %} {% block header %}
{% include 'header_search.html' %}
{% endblock %} {% block body %}
<main>
    <div class="results">
        {% for pyramid in pyramids %}
            
            
            <div class="result_brief {{ 'danger' if pyramid.status[0] == 1 }}">
                <div class="result_title textlinks ">
                    <a href="{{ url_for('pyramid.pyramid', snid=pyramid.sequence_number) }}">{{ _('Pyramid') }} {{ pyramid.sequence_number }}</a>
                    {% if pyramid.status[0] == 1 %}
                    <div class="textlinks align-flex-end" data-tooltip="{{ _('This pyramid is not valid. It\'ll be fixed as soon as posible') }}.">
                        <a class="material-symbols-outlined broken_info">help</a>
                    </div>
                    {% endif %}
                </div>

                <div class="data">
                    <span class="unit-description"><i>{{ _('Preview') }}</i></span>
                    <a href="{{ url_for('pyramid.pyramid', snid=pyramid.sequence_number) }}">{{ pyramid.gf_latex }}</a>
                </div>   
            </div>
            
        {% endfor %}
    </div>

    {% set left_b = page - 3 %}
    {% set right_b = page + 3 %}
    {% if left_b < 1 %}
    {% set left_b = 1 %}    
    {% endif %}
    {% if right_b > pages_in_total %}
    {% set right_b = pages_in_total %}    
    {% endif %}
    {% if pages_in_total != 1 %}
    <div class="nav_wrapper">
        <div class="page_nav textlinks">
            <span>{{ _('Page') }}:</span>
            {% if page - 4 > 1 %}
                <a href="{{ url_for('pyramid.pyramid_list', page=1) }}" class="page_nav-element">{{ 1 }}</a>
                <span>...</span>
            {% elif page - 4 == 1 %}
                <a href="{{ url_for('pyramid.pyramid_list', page=1) }}" class="page_nav-element">{{ 1 }}</a>
            {% endif %}
            

            {% for page_id in range(left_b, right_b+1) %}
                {% if page_id != page %}
                    <a href="{{ url_for('pyramid.pyramid_list', page=page_id) }}" class="page_nav-element">{{ page_id }}</a>
                {% else %}
                    <span class="page_nav-element">{{ page_id }}</span>
                {% endif %}
            {% endfor %}

            {% if page + 4 < pages_in_total %}
                <span>...</span>
                <a href="{{ url_for('pyramid.pyramid_list', page=pages_in_total) }}" class="page_nav-element">{{ pages_in_total }}</a>
            {% elif page + 4 == pages_in_total %}
                <a href="{{ url_for('pyramid.pyramid_list', page=pages_in_total) }}" class="page_nav-element">{{ pages_in_total }}</a>
            {% endif %}

        </div>
        <span>{{ _('or') }}</span>
        <div class="manual_page_input">
            <select class="page_nav-element pagenum" onchange="window.location.assign(`{{ url_for('pyramid.pyramid_list') }}` + '?page=' + this.options[this.selectedIndex].text)">
                {% for page_id in range(1, pages_in_total+1) %}
                    <option value="{{page_id}}" {% if page_id == page %}selected{% endif %}>{{page_id}}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    {% endif %}
</main>
{% endblock %}

encyclopedia/templates/search.html
{% extends 'base.html' %} {% block head %}
<title>{{q}} - {{ _('search results') }}</title>
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/katex.min.css"
  integrity="sha384-KiWOvVjnN8qwAZbuQyWDIbfCLFhLXNETzBQjA/92pIowpC0d2O3nppDGQVgwd2nB"
  crossorigin="anonymous"
/>
<script
  defer
  src="https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/katex.min.js"
  integrity="sha384-0fdwu/T/EQMsQlrHCCHoH10pkPLlKA1jL5dFyUOvB3lfeT2540/2g6YgSi2BL14p"
  crossorigin="anonymous"
></script>
<script
  defer
  src="https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/contrib/auto-render.min.js"
  integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR"
  crossorigin="anonymous"
></script>
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='stylesheets/tooltip.css') }}"
/>
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='stylesheets/pyramid_liststyle.css') }}"
/>

{% endblock %} {% block header %} {% include 'header_search.html' %} {% endblock
%} {% block body %}
<main>
  <div class="results" id="results"></div>

  <div class="nav_wrapper"></div>
</main>
{% endblock %} {% block afterscripts %}
<script src="/static/js/pagination.js"></script>
<script>
  window.onload = () => {
      init_variables({{exact|tojson}}, {{related|tojson}});
      display_results();
      display_nav();
  };
</script>
{% endblock %}

encyclopedia/templates/signup.html
{% extends 'base.html' %} {% block head %}
<link
  rel="stylesheet"
  href="{{ url_for('static',filename='stylesheets/forms__style.css') }}"
/>
<title>Sign up</title>
{% endblock %} {% block header %} {% include 'header_search.html' %} {% endblock
%} {% block body %}
<main>
  <form action="" method="post" class="form signup-form">
    {{ form.hidden_tag() }}

    <fieldset class="groups">
      <div class="title">{{ _('Sign up') }}</div>
      <div class="form-group">
        {{ form.username.label(class="groupelement-label") }} {% if
        form.username.errors %} {{ form.username(class="groupelement-input
        invalid") }}

        <div class="invalid-feedback">
          {% for error in form.username.errors%}
          <span>{{ error }}</span>
          {% endfor %}
        </div>

        {% else %} {{ form.username(class="groupelement-input") }} {% endif %}
      </div>
      <div class="form-group">
        {{ form.email.label(class="groupelement-label") }} {% if
        form.email.errors %} {{ form.email(class="groupelement-input invalid")
        }}
        <div class="invalid-feedback">
          {% for error in form.email.errors%}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{ form.email(class="groupelement-input") }} {% endif %}
      </div>
      <div class="form-group">
        {{ form.password.label(class="groupelement-label") }} {% if
        form.password.errors %} {{ form.password(class="groupelement-input
        invalid") }}
        <div class="invalid-feedback">
          {% for error in form.password.errors%}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{ form.password(class="groupelement-input") }} {% endif %}
      </div>
      <div class="form-group">
        {{ form.confirm_password.label(class="groupelement-label") }} {% if
        form.confirm_password.errors %} {{
        form.confirm_password(class="groupelement-input invalid") }}
        <div class="invalid-feedback">
          {% for error in form.confirm_password.errors%}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{ form.confirm_password(class="groupelement-input") }} {%
        endif %}
      </div>

      <div class="form-group form-submit">
        {{ form.submit(class="sumbitbtn groupelement-input growable") }}
      </div>
    </fieldset>
  </form>

  <div class="already">
    <small class="">
      {{ _('Already have an account') }}?
      <a href="{{ url_for('account.login') }}" class="signlink"
        >{{ _('Log in') }}</a
      >
    </small>
  </div>
</main>
{% endblock %}