app/encyclopedia/views/account.py
from encyclopedia.views import *

import os
import secrets
from werkzeug.utils import secure_filename


accountbp = Blueprint('account', __name__)

@accountbp.route('/login', methods=['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        flash(f'You already have been logged in!', 'info')
        return redirect(url_for('general.home'))

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if not user:
            user = User.query.filter_by(username=form.email.data.lower()).first()        

        if user and hasher.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash(f'Logged as {user.username.capitalize()}!', 'success')
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('general.home'))
        else:
            flash(f'Login unsuccessful. Please check email/username and password', 'danger')

    if request.method == 'POST':
        return redirect(url_for('general.search', q=request.form.get('pyramidinput')))

    return render_template('login.html', form=form)

@accountbp.route('/signup', methods=['POST', 'GET'])
def signup():
    if current_user.is_authenticated:
        flash(f'You already have been logged in!', 'danger')
        return redirect(url_for('general.home'))

    form = SignupForm()

    if form.validate_on_submit():
        hashed_pw = hasher.generate_password_hash(form.password.data).decode('utf-8')
        user = User(form.username.data.lower(), form.email.data.lower(), hashed_pw)
        db.session.add(user)
        db.session.commit()

        flash(f'Your account has been created! You are now able to log in!', 'success')
        return redirect(url_for('account.login'))

    if request.method == 'POST':
        return redirect(url_for('general.search', q=request.form.get('pyramidinput')))
    
    return render_template('signup.html', form=form)

@accountbp.route('/logout')
def logout():
    logout_user()
    
    return redirect(url_for('general.home'))

@accountbp.route('/<username>', methods=['POST', 'GET'])
@login_required
def account(username: str):
    user_account = User.query.filter_by(username=username).first() # user passed as an argument

    if not user_account:
        user_account = current_user
        return redirect(url_for('account.account', username=current_user.username))
    
    imagesrc = url_for('static', filename=f'profile_pictures/{user_account.profile_imagefile}')

    if request.method == 'POST':
        return redirect(url_for('general.search', q=request.form.get('pyramidinput')))

    return render_template('account.html', user=user_account, imagesrc=imagesrc)

@accountbp.route('/edit/<id>', methods=['POST', 'GET'])
@login_required
def update_profile(id: int):
    user_account = User.query.filter_by(id=id).first() # user passed as an argument
    form = UpdateProfileForm()

    if (not user_account) or (user_account != current_user):
        user_account = current_user
        return redirect(url_for('account.account', username=current_user.username))

    if form.validate_on_submit():
        if form.picture.data:
            picture_filepath = upload_file(form.picture.data, current_user.id)
            current_user.profile_imagefile = picture_filepath

        current_user.username = form.username.data.lower()
        current_user.email = form.email.data.lower()
        
        db.session.commit()
        flash('Your account has been edited!', 'success')

        return redirect(url_for('account.account', username=current_user.username))
    
    elif request.method == 'GET':
        form.username.data = current_user.username.capitalize()
        form.email.data = current_user.email.capitalize()

    imagesrc = url_for('static', filename=f'profile_pictures/{user_account.profile_imagefile}')

    if request.method == 'POST':
        return redirect(url_for('general.search', q=request.form.get('pyramidinput')))

    return render_template('update_profile.html', imagesrc=imagesrc, form=form)

def upload_file(form_file, user_id):
    new_filename = secrets.token_hex(8)
    new_filename += os.path.splitext(form_file.filename)[1]
    new_filename = secure_filename(new_filename)
    
    filedir = os.path.join(app.root_path, 'static', 'profile_pictures', str(user_id))
    if not os.path.isdir(filedir):
        print('Does not exist!', os.path.isfile(filedir))
        os.mkdir(filedir)
    
    filepath = os.path.join(filedir, new_filename)
    form_file.save(filepath)

    dbfilepath = f'{user_id}/{new_filename}'
    return dbfilepath

app/encyclopedia/views/pyramid.py
from encyclopedia.views import *

pyramidbp = Blueprint('pyramid', __name__)

@pyramidbp.route('/<snid>', methods=['POST', 'GET'])
def pyramid(snid: int):
    pyramid = Pyramid.query.filter_by(sequence_number=snid).first()

    if request.method == 'POST':
        return redirect(url_for('general.search', q=request.form.get('pyramidinput')))

    return render_template('pyramid.html', pyramid=pyramid, PyramidModel=Pyramid)


@pyramidbp.route('/upload', methods=['POST', 'GET'])
@login_required
def upload_pyramid():
    if not current_user.moderator:
        flash("You have no access to this page", "danger")
        return redirect(url_for("general.home"))
        
    form = UploadPyramidForm()

    if form.validate_on_submit():
        alreadyExist = Pyramid.query.filter_by(sequence_number=form.sequenceNumber.data).count() > 0
        if alreadyExist:
            flash(f'Such pyramid already exists', 'danger')
            return redirect(url_for('pyramid.upload_pyramid'))

        pyramid = Pyramid(form.sequenceNumber.data)
        


        rels = form.relations.data
        
        for i, gf in enumerate(form.generatingFunction):
            isMain = False
            if gf.f_name.data == 'U' or gf.f_name.data == 'u' or i == len(form.generatingFunction) - 1:
                isMain = True
            pyramid.add_generating_function(gf.f_name.data, gf.f_vars.data, gf.f_expr.data, isMain)
        
        for ef in form.explicitFormula:
            pyramid.add_explicit_formula(form.ef_vars.data, ef.f_expr.data, ef.f_condition.data)

        pyramid.init_special_value()
        # print(pyramid.init_special_value)
        alreadyExist = Pyramid.query.filter_by(__special_hashed_value__=pyramid.__special_hashed_value__).count() > 0
        
        if alreadyExist:
            flash(f'Such pyramid already exists', 'danger')
            return redirect(url_for('pyramid.upload_pyramid'))

        db.session.add(pyramid)

        if rels != '':
            for rel in rels.split(','):
                try:
                    rel = int(rel)
                    related_pyramid = Pyramid.query.filter_by(sequence_number = rel).first()
                    if related_pyramid is None:
                        flash(f'Could not get Pyramid#{rel}', 'danger')
                    else:
                        pyramid.add_relation(related_pyramid)
                except ValueError:
                    flash(f'Could not convert Pyramid #{pyramid.sequence_number} relation {rel} to int', 'danger')

        current_user.add_pyramid(pyramid)
        db.session.commit()
        flash('The pyramid has been added!', 'success')

        return redirect(url_for('general.home', username=current_user.username))
    
    if request.method == 'POST':
        return redirect(url_for('general.search', q=request.form.get('pyramidinput')))
    
    return render_template('upload_pyramid.html', form=form)

@pyramidbp.route('/<snid>/edit', methods=['POST', 'GET'])
@login_required
def edit_pyramid(snid: int):
    if not current_user.moderator:
        flash("You have no access to this page", "danger")
        return redirect(url_for("general.home"))
        
    form = UploadPyramidForm()
    pyramid = Pyramid.query.filter_by(sequence_number=snid).first()

    if form.validate_on_submit():
        rels = form.relations.data

        for i, gf in enumerate(form.generatingFunction):
            isMain = False
            if gf.f_name.data == 'U' or gf.f_name.data == 'u' or i == len(form.generatingFunction) - 1:
                isMain = True
            
            try:
                pyramid.generating_function[i].change_formula(
                        function_name=gf.f_name.data, 
                        variables=gf.f_vars.data, 
                        expression=gf.f_expr.data, 
                    )
            except IndexError:
                pyramid.add_generating_function(gf.f_name.data, gf.f_vars.data, gf.f_expr.data, isMain)
        
        for i, ef in enumerate(form.explicitFormula):
            try:
                pyramid.explicit_formula[i].change_formula(
                    expression=ef.f_expr.data, 
                    variables=form.ef_vars.data,
                    limitation=ef.f_condition.data
                )
            except IndexError:
                pyramid.add_explicit_formula(form.ef_vars.data, ef.f_expr.data, ef.f_condition.data)
        
        if form.relations.data != pyramid.get_relations_as_str():
            # pyramid.relations = []
            for relation in pyramid.relations.all():
                pyramid.delete_relation(relation)
            for rel in form.relations.data.split(','):
                related = Pyramid.query.filter_by(sequence_number=int(rel)).first()
                pyramid.add_relation(related)


        pyramid.init_special_value()
        db.session.commit()
        flash('The pyramid has been edited!', 'success')

        return redirect(url_for('pyramid.pyramid', snid=pyramid.sequence_number))
    
    elif request.method == 'GET':
        form.sequenceNumber.data = pyramid.sequence_number
        form.generatingFunction[0].f_name.data = pyramid.generating_function[0].function_name
        form.generatingFunction[0].f_vars.data = pyramid.generating_function[0].get_variables_as_str()
        form.generatingFunction[0].f_expr.data = pyramid.generating_function[0].expression

        form.ef_name.data = pyramid.explicit_formula[0].function_name
        form.ef_vars.data = pyramid.explicit_formula[0].get_variables_as_str()
        form.explicitFormula[0].f_expr.data = pyramid.explicit_formula[0].expression
        form.explicitFormula[0].f_condition.data = pyramid.explicit_formula[0].limitation

        for i in range(len(pyramid.generating_function) - 1):
            gf = pyramid.generating_function[i+1]
            gform = GeneratingFunctionForm()
            gform.f_name = gf.function_name
            gform.f_vars = gf.get_variables_as_str()
            gform.f_expr = gf.expression
            form.generatingFunction.append_entry(gform)

        for i in range(len(pyramid.explicit_formula) - 1):
            ef = pyramid.explicit_formula[i+1]
            eform = ExplicitFormulaForm()
            eform.f_expr=ef.expression
            eform.f_condition=ef.limitation
            form.explicitFormula.append_entry(eform)

        form.relations.data = pyramid.get_relations_as_str()
    
    if request.method == 'POST':
        return redirect(url_for('general.search', q=request.form.get('pyramidinput')))
    
    return render_template('upload_pyramid.html', form=form, pyramid=pyramid)

app/encyclopedia/templates/account.html
{% extends 'base.html' %} {% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/accountstyle.css') }}">
<title>User {{ user.username.capitalize() }}</title>
{% endblock %} {% block header %} 
    {% include 'header_search.html' %}
{% endblock %} {% block body %}
<main>
    <div class="content-wrapper">
        <div class="media">
            <div class="userimage">
                <img 
                src="{{ imagesrc }}" 
                alt="" class="profile-image" width="128" height="128">
            </div>
            <div class="userinfo">
                <div class="username"> {{ user.username.capitalize() }} </div>
                <div class="email"> {{ user.email.capitalize() }} </div>
            </div>
        </div>
            
            {% if current_user.id == user.id %}
                <a href="{{ url_for('account.update_profile', id=user.id) }}" class="link edit_profile"> 
                    <span class="material-icons">mode</span> Edit profile</a>
            {% endif %}
    </div>
</main>
{% endblock %}

app/encyclopedia/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/basestyle.css') }}">
    {% block head %} {% endblock %}
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <div class=flashes>
            {% for category, message in messages %}
                <div class="alert {{ category }}" onmouseover="prolongtimeout()">
                    <span>{{ message }}</span>
                    <span class="material-icons closebtn" onclick="close_alert(event)">close</span>
                </div>
            {% endfor %}
            </div>
            <script src="/static/js/notifications.js"></script>
        {% endif %}
    {% endwith %}
    <script>
        MathJax = {
            tex: {
                inlineMath: [
                    ['$', '$'],
                    ['\\(', '\\)']
                ]
            },
            svg: {
                fontCache: 'global',
            },
            startup: {
                ready: () => {
                    MathJax.startup.defaultReady();
                    MathJax.startup.promise.then(() => {
                        console.log('MathJax initial typesetting complete');
                    });
                }
            },
            tex2jax: {
                preview: "none"
            }
        };
    </script> 
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
</head>

<body onscroll="gotop()">
    <header>
        <span class="header_name">
            <a href="/">Online encyclopedia of Number Pyramids</a>
        </span> {% block header %} {% endblock %}
        
        <div class="btns">
            {% if current_user.is_authenticated %}
            {% if current_user.moderator %}
            <a href="{{ url_for('pyramid.upload_pyramid') }}" class="link"> Upload pyramid </a>
            {% endif %}
            
            <a href="{{ url_for('account.account', username=current_user.username) }}" class="account">
                <img
                src="{{ url_for('static', filename='profile_pictures/' + current_user.profile_imagefile|safe )}}"
                alt="{{ current_user.username.capitalize() }}"
                title="{{ current_user.username.capitalize() }}"
                width="40" height="40"
                class="profile_img">
            </a>
            <a href="{{ url_for('account.logout')}}" class="link logout">Log out</a>
            {% else %}
            <a href="{{ url_for('account.login')}}" class="link login">Log in</a>
            <a href="{{ url_for('account.signup')}}" class="link signup">Sign up</a>
            {% endif %}
        </div>
        
    </header>
    <div class="site-wrapper">
        
        
        {% block body %} {% endblock %}
        
    </div>
    
    <a href="#" class="go-top">
        <span class="material-icons-outlined go-arrow top-arrow">expand_less</span>
    </a>
    
    <footer>
        <div class="credits">
            Fullstack temax co.
        </div>
    </footer>
</body>

{% block afterscripts %}{% endblock %}
<script src="/static/js/topdown-navigation.js"></script>
</html>

app/encyclopedia/templates/header_search.html
<link rel="stylesheet" href="{{ url_for('static',filename='stylesheets/header_search.css') }}"/>

<div class="search-div">
    <form method="post" class="search-form">
        <div class="search-wrapper">
            <div class="input-wrapper">
                <!-- <label for="pyramidinput" class="questionlabel"> -->
                    <input 
                        type="text" 
                        name="pyramidinput" 
                        class="question" 
                        id="pyramidinput" 
                        placeholder="Pyramid expression"
                        required autocomplete="off" />
                <!-- </label> -->
                <button type="submit" class="questionbtn" id="questionbtn"> <span class="material-icons">search</span> </button>
            </div>
        </div>
    </form>
</div>

app/encyclopedia/templates/home.html
{% extends 'base.html' %} {% block head %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/katex.min.css" integrity="sha384-KiWOvVjnN8qwAZbuQyWDIbfCLFhLXNETzBQjA/92pIowpC0d2O3nppDGQVgwd2nB" crossorigin="anonymous">
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/katex.min.js" integrity="sha384-0fdwu/T/EQMsQlrHCCHoH10pkPLlKA1jL5dFyUOvB3lfeT2540/2g6YgSi2BL14p" crossorigin="anonymous"></script>
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/homestyle.css') }}">
<script>
    document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
              {left: '$$', right: '$$', display: true},
              {left: '$', right: '$', display: false},
              {left: '\\(', right: '\\)', display: false},
              {left: '\\[', right: '\\]', display: true}
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
    });
</script>
<title>Home</title>
{% endblock %} {% block header %}
{% include 'header_search.html' %}
{% endblock %} {% block body %}
<main>
    <div class="results">
        {% for pyramid in pyramids %}
            <div class="result_brief">
                <div class="result_title textlinks">
                    <a href="{{ url_for('pyramid.pyramid', snid=pyramid.sequence_number) }}">Pyramid {{ pyramid.sequence_number }}</a>   
                </div>

                <div class="data">
                    <span class="unit-description"><i>Preview</i></span>
                    <a href="{{ url_for('pyramid.pyramid', snid=pyramid.sequence_number) }}">{{ pyramid.gf_latex }}</a>
                </div>   

                <div class="author">
                    <span class="unit-description"><i>Author</i></span>
                    <div class="author-credits textlinks">
                        <a href="{{ url_for('account.account', username=pyramid.author.username) }}" class="authorlink">
                            <img
                            src="{{ url_for('static', filename='profile_pictures/' + pyramid.author.profile_imagefile|safe )}}"
                            alt="{{ pyramid.author.username.capitalize() }}"
                            title="{{ pyramid.author.username.capitalize() }}"
                            width="40" height="40"
                            class="profile_img">
                       </a>
                        <a href="{{ url_for('account.account', username=pyramid.author.username) }}">{{ pyramid.author.username.capitalize() }} </a>
                    </div>
                </div>
            </div>
            
        {% endfor %}
    </div>

    {% set left_b = page - 3 %}
    {% set right_b = page + 3 %}
    {% if left_b < 1 %}
    {% set left_b = 1 %}    
    {% endif %}
    {% if right_b > pages_in_total %}
    {% set right_b = pages_in_total %}    
    {% endif %}
    {% if pages_in_total != 1 %}
    <div class="nav_wrapper">
        <div class="page_nav textlinks">
            <span>Page:</span>
            {% if page - 4 > 1 %}
                <a href="{{ url_for('general.home', page=1) }}" class="page_nav-element">{{ 1 }}</a>
                <span>...</span>
            {% elif page - 4 == 1 %}
                <a href="{{ url_for('general.home', page=1) }}" class="page_nav-element">{{ 1 }}</a>
            {% endif %}
            

            {% for page_id in range(left_b, right_b+1) %}
                {% if page_id != page %}
                    <a href="{{ url_for('general.home', page=page_id) }}" class="page_nav-element">{{ page_id }}</a>
                {% else %}
                    <span class="page_nav-element">{{ page_id }}</span>
                {% endif %}
            {% endfor %}

            {% if page + 4 < pages_in_total %}
                <span>...</span>
                <a href="{{ url_for('general.home', page=pages_in_total) }}" class="page_nav-element">{{ pages_in_total }}</a>
            {% elif page + 4 == pages_in_total %}
                <a href="{{ url_for('general.home', page=pages_in_total) }}" class="page_nav-element">{{ pages_in_total }}</a>
            {% endif %}

        </div>
        <span>or</span>
        <div class="manual_page_input">
            <select class="page_nav-element pagenum" onchange="window.location.assign(`{{ url_for('general.home') }}` + '?page=' + this.options[this.selectedIndex].text)">
                {% for page_id in range(1, pages_in_total+1) %}
                    <option value="{{page_id}}" {% if page_id == page %}selected{% endif %}>{{page_id}}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    {% endif %}
</main>
{% endblock %}

app/encyclopedia/templates/login.html
{% extends 'base.html' %}
{% block head %}
<link rel="stylesheet" href="{{ url_for('static',filename='stylesheets/forms__style.css') }}"/>
<title>Log In</title>
{% endblock %} {% block header %}
{% include 'header_search.html' %}
{% endblock %} {% block body %}
<main>
    {% if error %}
        <p class=error><strong>Error:</strong> {{ error }}
    {% endif %}
    <form action="" method="post" class="form login-form">
        {{ form.hidden_tag() }}
        
        <fieldset class="groups">
            <div class="form-group title">Log In</div>
            <div class="form-group">
                {{ form.email.label(class="groupelement-label") }}
                {{ form.email(class="groupelement-input") }}
            </div>
            <div class="form-group">
                {{ form.password.label(class="groupelement-label") }}
                {{ form.password(class="groupelement-input", autocomplete="off") }}
            </div>

            <div class="form-group remember">
                {{ form.remember_me(class="remember_me-input") }}
                {{ form.remember_me.label(class="remember_me-label") }}
            </div>

            <div class="form-group form-submit">
                {{ form.submit(class="sumbitbtn groupelement-input") }}
            </div>
        </fieldset>

        
    </form>
    <div class="already">
        <small class="">
            Don't have an account? <a href="{{ url_for('account.signup') }}" class="signlink">Sign up</a> 
        </small>
    </div>
</main>
{% endblock %}

app/encyclopedia/templates/not_found.html
{% extends 'base.html' %} {% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/not_foundstyle.css') }}">
<title>{{ user_input }}</title>
{% endblock %} {% block header %}
    {% include 'header_search.html' %}
{% endblock %} {% block body %}
<main>
    <div class="notfound">
        <span>Your search -<b> 
            {% if user_input|length > 25 %}{{ user_input[0:25] }}...{% else %}{{ user_input }}{% endif %}
            </b>- did not match anything.</span>
        <span>Try going back <a href="/">home</a> and perform another search.</span>
    </div>
</main>
{% endblock %}

app/encyclopedia/templates/page_not_found.html
{% extends 'base.html' %} {% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/not_foundstyle.css') }}">
<title>Page not found</title>
{% endblock %} {% block header %}
    {% include 'header_search.html' %}
{% endblock %} {% block body %}
<main>
    <div class="notfound">
        <span>Sorry, there's no such page. You can try going <a href="/">home</a> and explore the pyramid.</span>
    </div>
</main>
{% endblock %}

app/encyclopedia/templates/pyramid.html
{% extends 'base.html' %} {% block head %}
<link rel="stylesheet" href="{{ url_for('static',filename='stylesheets/pyramidstyle.css') }}">
<title>Pyramid {{ pyramid.sequence_number }} </title>
{% endblock %} {% block header %}
{% include 'header_search.html' %}
{% endblock %} {% block body %}
<main>
    {% if current_user.is_authenticated and current_user.moderator  %}
        <a href="{{ url_for('pyramid.edit_pyramid', snid=pyramid.sequence_number) }}" class="link edit_pyramid"> Edit pyramid </a>
    {% endif %}

    <div class="content-wrapper"> <!-- Generating function -->
        <div class="pyramid_navigation">
            <div class="textlinks nav">
                {% if PyramidModel.query.filter_by(sequence_number=pyramid.sequence_number-1).count() > 0 %}
                    <a href="{{ url_for('pyramid.pyramid', snid=pyramid.sequence_number-1) }}">Pyramid #{{ pyramid.sequence_number - 1 }}</a>
                {% endif %}
            </div>            
            <span class="pnum"> Pyramid #{{ pyramid.sequence_number }} </span>
            <div class="textlinks nav">
                {% if PyramidModel.query.filter_by(sequence_number=pyramid.sequence_number+1).count() > 0 %}
                <a href="{{ url_for('pyramid.pyramid', snid=pyramid.sequence_number+1) }}">Pyramid #{{ pyramid.sequence_number + 1 }}</a>
                {% endif %}
            </div>
            
        </div>        
        <span class="title"> Generating function </span>
        <div class="latex">
            {{ pyramid.gf_latex }}
        </div>
    </div>

    <div class="content-wrapper"> <!-- Explicit Formula -->
        <span class="title"> Explicit formula </span>
        <div class="latex">
            {{ pyramid.ef_latex }}
        </div>

    </div>

    <div class="content-wrapper">
        {% set n = 7 %}
        {% set m = 7 %}
        {% set k = 1 %}
        {% set data = pyramid.get_data_by_ef(n, m, k) %}
        <table>
            <caption>Data table</caption>
            <tbody>
                {% for i in range(n) %}
                    <tr>
                        {% for j in range(m) %}
                            <td> {{ data[(i*n) + j] }} </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="content-wrapper">
        <div class="title">Related</div>
        <div class="textlinks">
            {% for relation in pyramid.__get_relations_str__() %} 
                <a href="{{ url_for('pyramid.pyramid', snid=relation) }}"> {{ relation }} </a>
            {% endfor %}
        </div>
    </div>

    <div class="content-wrapper">
        <div class="title">Export</div>
        <div class="exportbtn-wrapper">
            <!-- <button class="exportbtn" id="maximabtn" onclick="show_modal('#maximacode')">Export as Maxima</button>
            <button class="exportbtn" id="mathematicabtn" onclick="show_modal('#mathematicacode')">Export as Mathematica</button> -->
            <button class="exportbtn" id="latexbtn" onclick="show_modal('#latexcode')">Export as LaTEX</button>

            

            <div class="modalwindow" id="latexcode" onclick="close_modal(event)"> <!-- LaTEX -->
                <div class="exportcode-wrapper">
                    <div class="exportcode-header">
                        <div class="title">Export as LaTEX</div> 
                        <div class="closebtn"><span class="material-icons">close</span></div>
                    </div>
                    <textarea class="exportcode" readonly>{{ pyramid.gf_latex.replace("$","")|safe }}&#13;&#10;{{ pyramid.ef_latex.replace("$","")|safe }}</textarea>
                    <div class="exportcopybtn-wrapper"> <button class="copybtn" onclick="copy()">Copy</button> </div>
                </div>
            </div>


        </div>
    </div>
</main>
{% endblock %}

{% block afterscripts %}
    <script src="/static/js/export.js"></script>
{% endblock %}

app/encyclopedia/templates/upload.html
{% extends 'base.html' %} {% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/not_foundstyle.css') }}">
<title>{{ user_input }}</title>
{% endblock %} {% block body %}
<main>
    <form action="getfile" method="POST" enctype="multipart/form-data">
        Project file path: <input type="file" name="myfile"><br>
        <input type="submit" value="Submit">
    </form>
</main>
{% endblock %}